# serverless.yml
service: taxdown-customer-api
frameworkVersion: '4'


provider:
  name: aws
  runtime: nodejs20.x
  region: us-west-2
  stage: ${opt:stage, 'dev'} # default stage
  environment:
    CUSTOMER_TABLE: ${self:service}-customers-${opt:stage, 'dev'}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:Scan
      Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.CUSTOMER_TABLE}

functions:
  api:
    handler: src/index.handler
    events:
      - http:
          path: "api/v1/customers"
          method: get
          cors: true
      - http:
          path: "api/v1/customers"
          method: post
          cors: true
      - http:
          path: "api/v1/customers/{id}"
          method: get
          cors: true
      - http:
          path: "api/v1/customers/{id}"
          method: put
          cors: true
      - http:
          path: "api/v1/customers/{id}"
          method: delete
          cors: true
      - http:
          path: "api/v1/customers/{id}/add-credit"
          method: post
          cors: true

resources:
  Resources:
    CustomerTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.CUSTOMER_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

plugins:
  - serverless-domain-manager
  - serverless-offline

custom:
  customDomain:
    domainName: taxdown.alejandrogalaz.site
    basePath: ''
    stage: ${self:provider.stage}
    certificateName: "*.alejandrogalaz.site"
    createRoute53Record: true
    endpointType: "REGIONAL"